import { SELECT_EQUIPMENT_PRELOAD } from "@/const/ResourceUrl";
import { EquipmentKey, EquipmentType, type Equipment } from "./type";

// 最多能携带的装备体积
export const EQUIPMENT_MAX_SIZE = 55;
// 最多能携带的装备重量（kg）
export const EQUIPMENT_MAX_WEIGHT = 20;

export const EQUIPMENTS: Equipment[] = [
  // {
  //   key: EquipmentKey.LightTent,
  //   name: "轻便帐篷",
  //   weight: 1.2,
  //   size: 8,
  //   src: SELECT_EQUIPMENT_PRELOAD.LIGHT_TENT,
  //   useTime: 15,
  //   warm: 5,
  //   type: EquipmentType.Tent,
  //   isSelectEquipmentShow: true,
  // },
  // {
  //   key: EquipmentKey.WarmTent,
  //   name: "保暖帐篷",
  //   weight: 3,
  //   size: 12,
  //   src: SELECT_EQUIPMENT_PRELOAD.WARM_TENT,
  //   useTime: 30,
  //   warm: 8,
  //   type: EquipmentType.Tent,
  //   isSelectEquipmentShow: true,
  // },
  // {
  //   key: EquipmentKey.SleepingBag,
  //   name: "睡袋",
  //   weight: 1.8,
  //   size: 7,
  //   src: SELECT_EQUIPMENT_PRELOAD.SLEEPING_BAG,
  //   warm: 5,
  //   type: EquipmentType.Warmth,
  //   isSelectEquipmentShow: true,
  // },
  {
    key: EquipmentKey.FirstAidKit,
    name: "急救包",
    weight: 0.8,
    size: 2,
    src: SELECT_EQUIPMENT_PRELOAD.FIRST_AID_KIT,
    useTime: 10,
    disposable: true,
    type: EquipmentType.Medical,
    isSelectEquipmentShow: true,
  },
  {
    key: EquipmentKey.SurvivalBlanket,
    name: "救生毯",
    weight: 0.1,
    size: 0.5,
    src: SELECT_EQUIPMENT_PRELOAD.SURVIAL_BLANKET,
    disposable: true,
    warm: 20,
    type: EquipmentType.Warmth,
    isSelectEquipmentShow: true,
  },
  {
    key: EquipmentKey.MushroomJiYou,
    name: "蘑菇",
    weight: 0.2,
    size: 0.2,
    src: SELECT_EQUIPMENT_PRELOAD.MUSHROOM_JIYOU,
    disposable: true,
    type: EquipmentType.Food,
  },
  {
    key: EquipmentKey.MushroomXiangGu,
    name: "蘑菇",
    weight: 0.2,
    size: 0.2,
    src: SELECT_EQUIPMENT_PRELOAD.MUSHROOM_XIANGGU,
    disposable: true,
    type: EquipmentType.Food,
  },
  {
    key: EquipmentKey.MushroomDuYing,
    name: "蘑菇",
    weight: 0.2,
    size: 0.2,
    src: SELECT_EQUIPMENT_PRELOAD.MUSHROOM_DUYING,
    disposable: true,
    type: EquipmentType.Food,
  },
  {
    key: EquipmentKey.MushroomEGan,
    name: "蘑菇",
    weight: 0.2,
    size: 0.2,
    src: SELECT_EQUIPMENT_PRELOAD.MUSHROOM_EGAN,
    disposable: true,
    type: EquipmentType.Food,
  },
{
    key: EquipmentKey.Mushroom_JianShouQing,
    name: "蘑菇",
    weight: 0.2,
    size: 0.2,
    src: SELECT_EQUIPMENT_PRELOAD.MUSHROOM_JIANSHOUQING,
    disposable: true,
    type: EquipmentType.Food,
  },

  {
    key: EquipmentKey.SportsDrink,
    name: "运动饮料",
    weight: 0.55,
    size: 0.5,
    src: SELECT_EQUIPMENT_PRELOAD.SPORTS_DRINK,
    disposable: true,
    type: EquipmentType.Food,
    isSelectEquipmentShow: true,
  },
  {
    key: EquipmentKey.CompressedBiscuit,
    name: "压缩饼干",
    weight: 0.3,
    size: 0.3,
    src: SELECT_EQUIPMENT_PRELOAD.COMPRESSED_BISCUIT,
    disposable: true,
    type: EquipmentType.Food,
    isSelectEquipmentShow: true,
  },
  {
    key: EquipmentKey.SelfHeatingPot,
    name: "自热锅",
    weight: 1.2,
    size: 2,
    src: SELECT_EQUIPMENT_PRELOAD.SELF_HEATING_POT,
    useTime: 10,
    disposable: true,
    warm: 10,
    type: EquipmentType.Food,
    isSelectEquipmentShow: true,
  },
  {
    key: EquipmentKey.BeastSteak,
    name: "野兽肉排",
    weight: 0.3,
    size: 0.4,
    src: SELECT_EQUIPMENT_PRELOAD.SELF_HEATING_POT,
    disposable: true,
    warm: 8,
    type: EquipmentType.Food,
  },
  {
    key: EquipmentKey.Egg,
    name: "鸡蛋",
    weight: 0.2,
    size: 1,
    src: SELECT_EQUIPMENT_PRELOAD.SELF_HEATING_POT,
    useTime: 10,
    disposable: true,
    warm: 10,
    type: EquipmentType.Food,
  },
  {
    key: EquipmentKey.Spear,
    name: "长矛",
    weight: 0.2,
    size: 0.2,
    // WIP
    src: SELECT_EQUIPMENT_PRELOAD.SPORTS_DRINK,
    type: EquipmentType.Tool,
  },
  {
    key: EquipmentKey.HikingPole,
    name: "登山杖",
    weight: 0.3,
    size: 0,
    src: SELECT_EQUIPMENT_PRELOAD.HIKING_POLE,
    type: EquipmentType.Tool,
    isSelectEquipmentShow: true,
  },
  {
    key: EquipmentKey.Crampons,
    name: "冰爪",
    weight: 0.8,
    size: 2,
    src: SELECT_EQUIPMENT_PRELOAD.CRAMPONS,
    type: EquipmentType.Tool,
    isSelectEquipmentShow: true,
  },
  {
    key: EquipmentKey.BearBell,
    name: "熊铃",
    weight: 0.05,
    size: 0,
    src: SELECT_EQUIPMENT_PRELOAD.BEAR_BELL,
    type: EquipmentType.Tool,
    isSelectEquipmentShow: true,
  },
  {
    key: EquipmentKey.PowerBank,
    name: "充电宝",
    weight: 0.3,
    size: 0.4,
    src: SELECT_EQUIPMENT_PRELOAD.POWER_BANK,
    type: EquipmentType.Daily,
    isSelectEquipmentShow: true,
  },
  {
    key: EquipmentKey.Headlamp,
    name: "头灯",
    weight: 0.2,
    size: 0.2,
    src: SELECT_EQUIPMENT_PRELOAD.HEAD_LAMP,
    type: EquipmentType.Daily,
    isSelectEquipmentShow: true,
  },
];
